Update requirements.txt
NLP-kr/tensorflow-ml-nlp-tf2 pull request #14
Opened 2020-12-22 12:11 UTC by sk8erchoi

설치 시 발생하는 몇 가지 문제를 해결했습니다.

2020-12-23 09:17 UTC, aiscientist requested changes
현재 학습 프로세스상 wget==3.2 / tokenizers==0.8.1.rc1가 필수적으로 들어가야 할 듯 합니다.

2020-12-23 10:28 UTC, sk8erchoi commented
수정했습니다.

2020-12-23 15:26 UTC, Taekyoon commented
이렇게 자세하게 보완 업데이트를 남겨주셔서 감사합니다.
그리고 몇 가지 여쭙고 싶은게 있습니다.

transformers 라이브러리를 버전 2.11 이상으로 설정을 해두셨는데요.
transformers 같은경우 업데이트가 자주 일어나고 향후에 업데이트에 의해서 저희 구현에 문제가 생길 여지가 있지 않을까 싶습니다.
transformers==2.11.0 으로 해두는 것이 어떨까 싶습니다.

추가로 저희 실습파일들은 전체적으로 tensorflow==2.2.0 기반으로 테스트를 진행했었는데요. 
이 점도 같이 봐주실 수 있을까요?

추가로 위 requirements.txt를 저희 책에 올려둔 도커파일과도 테스트를 해보셨을지 궁금합니다.

2020-12-23 17:22 UTC, sk8erchoi commented
transformers==2.11.0로 설정하면 다음 오류가 발생합니다.

ERROR: Cannot install -r requirements.txt (line 10) and tokenizers==0.8.1.rc1 because these package versions have conflicting dependencies.

이번에 tokenizers==0.8.1.rc1와 transformers>=2.11.0을 함께 지정했을 때는 아래와 같이 설치가 잘 되었습니다.

Successfully installed tokenizers-0.8.1rc1 transformers-3.0.2

도커 파일은 테스트를 안 해봤는데 한번 해보고 알려드리겠습니다.

2020-12-24 16:36 UTC, sk8erchoi commented
mxnet 1.6.0을 쓰려면 request 2.18.4가 필요하고, 그에 맞는 tensorboard 버전은 2.0.0, tensorflow 버전은 2.0.3이 됩니다. 즉, tensorflow 2.2.0과 mxnet 1.6.0을 함께 설치할 수 없었습니다. 제가 작성한 requirements.txt에 tensorflow 버전을 2.0.3으로 한 것이 그 때문입니다.

여러 가지 조합으로 테스트하면서 아래와 같은 메시지를 확인했습니다.
tensorflow 2.2.0 depends on tensorboard<2.3.0 and >=2.2.0
tensorflow 2.1.2 depends on tensorboard<2.2.0 and >=2.1.0
tensorflow 2.0.3 depends on tensorboard<2.1.0 and >=2.0.0
tensorboard 2.2.0 depends on requests<3 and >=2.21.0
tensorboard 2.0.2 depends on requests<3 and >=2.21.0
mxnet 1.7.0.post1 depends on requests<2.19.0 and >=2.18.4
mxnet 1.6.0 depends on requests<2.19.0 and >=2.18.4

도커 환경으로 테스트는 못 해봤습니다만, [도커 파일](https://github.com/NLP-kr/tensorflow-ml-nlp-tf2/blob/master/Dockerfile_gpu) 첫 줄에 FROM tensorflow/tensorflow:2.2.0-gpu로 되어 있는 걸로 봐서는 역시 2.2.0 버전으로 작성하신 것 같습니다.

2020-12-26 06:07 UTC, Taekyoon commented
네 말씀하신 원인에 대해서 잘 이해했습니다.
결과적으로 모든 실습파일에 대해서 동작이 잘되니 tf 2.2.0으로 굳이 fix될 필요는 없어보입니다.
우선 merge 하고 추후에 발생하는 문제가 있을 시 대응하면 될 것 같습니다.

2020-12-26 06:07 UTC, merged